# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1216, 662)
        MainWindow.setStyleSheet("QMainWindow {\n"
"}\n"
"\n"
"QLineEdit {\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    padding: 4px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(80, 250, 81, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(670, 150, 91, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(630, 100, 132, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.et_databaseName = QtWidgets.QLineEdit(self.centralwidget)
        self.et_databaseName.setGeometry(QtCore.QRect(770, 110, 371, 25))
        self.et_databaseName.setStyleSheet("QLineEdit {\n"
"    border-radius: 8px;\n"
"    border: 1px solid rgb(53, 132, 228);\n"
"}")
        self.et_databaseName.setObjectName("et_databaseName")
        self.et_companyName = QtWidgets.QLineEdit(self.centralwidget)
        self.et_companyName.setGeometry(QtCore.QRect(180, 310, 371, 25))
        self.et_companyName.setStyleSheet("QLineEdit {\n"
"    border-radius: 8px;\n"
"    border: 1px solid rgb(53, 132, 228);\n"
"}")
        self.et_companyName.setObjectName("et_companyName")
        self.et_serverName = QtWidgets.QLineEdit(self.centralwidget)
        self.et_serverName.setGeometry(QtCore.QRect(180, 110, 371, 25))
        self.et_serverName.setStyleSheet("QLineEdit {\n"
"    border-radius: 8px;\n"
"    border: 1px solid rgb(53, 132, 228);\n"
"}")
        self.et_serverName.setObjectName("et_serverName")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(660, 250, 91, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(630, 350, 131, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 150, 91, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.settings_icon = QtWidgets.QLabel(self.centralwidget)
        self.settings_icon.setGeometry(QtCore.QRect(20, 10, 71, 71))
        self.settings_icon.setPixmap(QtGui.QPixmap("../../Downloads/settingsicon.png"))
        self.settings_icon.setScaledContents(True)
        self.settings_icon.setObjectName("settings_icon")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 100, 112, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.et_userName = QtWidgets.QLineEdit(self.centralwidget)
        self.et_userName.setGeometry(QtCore.QRect(180, 160, 371, 25))
        self.et_userName.setStyleSheet("QLineEdit {\n"
"    border-radius: 8px;\n"
"    border: 1px solid rgb(53, 132, 228);\n"
"}")
        self.et_userName.setObjectName("et_userName")
        self.et_printerPid = QtWidgets.QLineEdit(self.centralwidget)
        self.et_printerPid.setGeometry(QtCore.QRect(770, 210, 371, 25))
        self.et_printerPid.setStyleSheet("QLineEdit {\n"
"    border-radius: 8px;\n"
"    border: 1px solid rgb(53, 132, 228);\n"
"}")
        self.et_printerPid.setObjectName("et_printerPid")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(90, 20, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setTextFormat(QtCore.Qt.PlainText)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 300, 131, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.et_zplCommand = QtWidgets.QTextEdit(self.centralwidget)
        self.et_zplCommand.setGeometry(QtCore.QRect(770, 360, 371, 191))
        self.et_zplCommand.setMinimumSize(QtCore.QSize(0, 0))
        self.et_zplCommand.setStyleSheet("QTextEdit {\n"
"    border: 1px solid rgb(53, 132, 228);\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"}")
        self.et_zplCommand.setObjectName("et_zplCommand")
        self.et_tpslCommand = QtWidgets.QTextEdit(self.centralwidget)
        self.et_tpslCommand.setGeometry(QtCore.QRect(180, 360, 371, 191))
        self.et_tpslCommand.setStyleSheet("QTextEdit {\n"
"    border: 1px solid rgb(53, 132, 228);\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"}")
        self.et_tpslCommand.setObjectName("et_tpslCommand")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 350, 141, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 200, 101, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.et_endPoint = QtWidgets.QLineEdit(self.centralwidget)
        self.et_endPoint.setGeometry(QtCore.QRect(180, 260, 371, 25))
        self.et_endPoint.setStyleSheet("QLineEdit {\n"
"    border-radius: 8px;\n"
"    border: 1px solid rgb(53, 132, 228);\n"
"}")
        self.et_endPoint.setObjectName("et_endPoint")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(990, 580, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btn_save.setFont(font)
        self.btn_save.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0.148, y1:1, x2:1, y2:1, stop:0.233503 rgba(53, 132, 228, 255), stop:1 rgba(26, 95, 180, 255));\n"
"    color: white;\n"
"    border-top-left-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"    qproperty-cursor: pointingHandCursor;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-radius: 18px;\n"
"    \n"
"\n"
"}")
        self.btn_save.setObjectName("btn_save")
        self.et_commandLanguage = QtWidgets.QLineEdit(self.centralwidget)
        self.et_commandLanguage.setGeometry(QtCore.QRect(770, 260, 371, 25))
        self.et_commandLanguage.setStyleSheet("QLineEdit {\n"
"    border-radius: 8px;\n"
"    border: 1px solid rgb(53, 132, 228);\n"
"}")
        self.et_commandLanguage.setObjectName("et_commandLanguage")
        self.et_location = QtWidgets.QLineEdit(self.centralwidget)
        self.et_location.setGeometry(QtCore.QRect(770, 310, 371, 25))
        self.et_location.setStyleSheet("QLineEdit {\n"
"    border-radius: 8px;\n"
"    border: 1px solid rgb(53, 132, 228);\n"
"}")
        self.et_location.setObjectName("et_location")
        self.btn_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cancel.setGeometry(QtCore.QRect(820, 580, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(53, 132, 228);\n"
"    border-top-left-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"    qproperty-cursor: pointingHandCursor;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-radius: 18px;\n"
"}")
        self.btn_cancel.setObjectName("btn_cancel")
        self.et_password = QtWidgets.QLineEdit(self.centralwidget)
        self.et_password.setGeometry(QtCore.QRect(770, 160, 371, 25))
        self.et_password.setStyleSheet("QLineEdit {\n"
"    border-radius: 8px;\n"
"    border: 1px solid rgb(53, 132, 228);\n"
"}")
        self.et_password.setObjectName("et_password")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(660, 200, 91, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.et_printerVid = QtWidgets.QLineEdit(self.centralwidget)
        self.et_printerVid.setGeometry(QtCore.QRect(180, 210, 371, 25))
        self.et_printerVid.setStyleSheet("QLineEdit {\n"
"    border-radius: 8px;\n"
"    border: 1px solid rgb(53, 132, 228);\n"
"}")
        self.et_printerVid.setObjectName("et_printerVid")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(670, 300, 81, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.img_label = QtWidgets.QLabel(self.centralwidget)
        self.img_label.setGeometry(QtCore.QRect(0, 0, 1221, 801))
        self.img_label.setText("")
        self.img_label.setPixmap(QtGui.QPixmap("../../Pictures/vector-JUL-2021-61.jpg"))
        self.img_label.setScaledContents(True)
        self.img_label.setObjectName("img_label")
        self.img_label.raise_()
        self.label_7.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.et_databaseName.raise_()
        self.et_companyName.raise_()
        self.et_serverName.raise_()
        self.label_8.raise_()
        self.label_10.raise_()
        self.label_4.raise_()
        self.settings_icon.raise_()
        self.label_5.raise_()
        self.et_userName.raise_()
        self.et_printerPid.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.et_zplCommand.raise_()
        self.et_tpslCommand.raise_()
        self.label_9.raise_()
        self.label_6.raise_()
        self.et_endPoint.raise_()
        self.btn_save.raise_()
        self.et_commandLanguage.raise_()
        self.et_location.raise_()
        self.btn_cancel.raise_()
        self.et_password.raise_()
        self.label_13.raise_()
        self.et_printerVid.raise_()
        self.label_15.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Endpoint:"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.label_2.setText(_translate("MainWindow", "Database Name:"))
        self.label_8.setText(_translate("MainWindow", "Command:"))
        self.label_10.setText(_translate("MainWindow", "ZPL Command:"))
        self.label_4.setText(_translate("MainWindow", "Username:"))
        self.label_5.setText(_translate("MainWindow", "Server Name:"))
        self.label_11.setText(_translate("MainWindow", "Settings"))
        self.label_12.setText(_translate("MainWindow", "Company Name:"))
        self.et_zplCommand.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Fira Sans Semi-Light\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">SPEED 2.0 </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">DENSITY 7 </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">DIRECTION 0 </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">SIZE 35MM,25MM </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">OFFSET 0.000 </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">REFERENCE 0,0 </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CLS </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TEXT 320,5,\\&quot;2\\&quot;,0,1,1,\\&quot;{{companyName}}\\&quot; </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TEXT 310,40,\\&quot;2\\&quot;,0,1,1,\\&quot;{{barcode_value}}\\&quot; </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TEXT 310,120,\\&quot;1\\&quot;,0,1,1,\\&quot;{{description}}\\&quot; </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">BARCODE 310,60,\\&quot;128\\&quot;,50,0,0,2,10,\\&quot;{{barcode_value}}\\&quot; </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TEXT 310,160,\\&quot;4\\&quot;,0,1,1,\\&quot;{{unit_price_integer}}\\&quot; </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">PRINT {{copies}} </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">EOP</p></body></html>"))
        self.et_tpslCommand.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Fira Sans Semi-Light\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">SPEED 2.0 </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">DENSITY 7 </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">DIRECTION 0 </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">SIZE 35MM,25MM </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">OFFSET 0.000 </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">REFERENCE 0,0 </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CLS </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TEXT 320,5,\\&quot;2\\&quot;,0,1,1,\\&quot;{{companyName}}\\&quot; </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TEXT 310,40,\\&quot;2\\&quot;,0,1,1,\\&quot;{{barcode_value}}\\&quot; </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TEXT 310,120,\\&quot;1\\&quot;,0,1,1,\\&quot;{{description}}\\&quot; </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">BARCODE 310,60,\\&quot;128\\&quot;,50,0,0,2,10,\\&quot;{{barcode_value}}\\&quot; </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TEXT 310,160,\\&quot;4\\&quot;,0,1,1,\\&quot;{{unit_price_integer}}\\&quot; </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">PRINT {{copies}} </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">EOP</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "TPSL Command:"))
        self.label_6.setText(_translate("MainWindow", "Printer Vid:"))
        self.btn_save.setText(_translate("MainWindow", "Save"))
        self.btn_cancel.setText(_translate("MainWindow", "Cancel"))
        self.label_13.setText(_translate("MainWindow", "Printer Pid:"))
        self.label_15.setText(_translate("MainWindow", "Location:"))
